version: "3"

services:

  db:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: user
      POSTGRES_DB: shop
    ports:
      - 5431:5432
    networks:
      - shop_net


  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
    networks:
      - shop_net


  shop_server:
    build: server/
    environment:
      DB_PORT: 5432
      DB_NAME: shop
      DB_USER: user
      DB_PASSWORD: 123
      DB_HOST: db
      DB_SSLMODE: disable
    ports:
      - 8081:8080
    networks:
      - shop_net


  auth:
    build: auth/
    environment:
      DB_PORT: 5432
      DB_NAME: shop
      DB_USER: user
      DB_PASSWORD: 123
      DB_HOST: db
      DB_SSLMODE: disable
      ACCESS_TOKEN_KEY: 123
      CONFIRM_TOKEN_KEY: 321
      RABBITMQ: amqp://guest:guest@rabbitmq:5672/
    ports:
      - 8082:8080
    networks:
      - shop_net
  

  notifications:
    build: notifications/
    environment:
      RABBITMQ: amqp://guest:guest@rabbitmq:5672/
      SMTP_SERVER: mock
      FROM_EMAIL: test@mock
      PASSWORD: 1
    networks:
      - shop_net


  mock:
    build: mock/
    networks:
      - shop_net

networks:
    shop_net: