version: "3"

services:

  db:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: user
      POSTGRES_DB: shop
    ports:
      - 5431:5432
    networks:
      - shop_net


  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
    networks:
      - shop_net


  shop_server:
    build:
      dockerfile: server/Dockerfile
      context: .
    environment:
      DB_PORT: 5432
      DB_NAME: shop
      DB_USER: user
      DB_PASSWORD: 123
      DB_HOST: db
      DB_SSLMODE: disable
    ports:
      - 8081:8080
    networks:
      - shop_net


  auth:
    build:
      dockerfile: auth/Dockerfile
      context: .
    environment:
      DB_PORT: 5432
      DB_NAME: shop
      DB_USER: user
      DB_PASSWORD: 123
      DB_HOST: db
      DB_SSLMODE: disable
      GRPC_PORT: :50051
      ACCESS_TOKEN_KEY: 123
      CONFIRM_TOKEN_KEY: 321
      RABBITMQ: amqp://guest:guest@rabbitmq:5672/
    ports:
      - 8082:8080
    networks:
      - shop_net
  

  notifications:
    build:
      dockerfile: notifications/Dockerfile
      context: .
    environment:
      RABBITMQ: amqp://guest:guest@rabbitmq:5672/
      SMTP_SERVER: mock
      FROM_EMAIL: test@mock
      PASSWORD: 1
    networks:
      - shop_net


  product_upload:
    build:
      dockerfile: product_upload/Dockerfile
      context: .
    environment:
      RABBITMQ: amqp://guest:guest@rabbitmq:5672/
    ports:
        - 8083:8080
    networks:
      - shop_net
  
  product_upload_inserter:
    build: 
      dockerfile: product_upload_inserter/Dockerfile
      context: .
    environment:
      DB_PORT: 5432
      DB_NAME: shop
      DB_USER: user
      DB_PASSWORD: 123
      DB_HOST: db
      DB_SSLMODE: disable
      RABBITMQ: amqp://guest:guest@rabbitmq:5672/
    networks:
      - shop_net


  mock:
    build:
      dockerfile: mock/Dockerfile
      context: .
    networks:
      - shop_net

networks:
    shop_net: